### ISSUE TITLE
Wczytywanie pliku konfiguracji

### ISSUE THREAD

**Issue by maxmati** [zmora-agh/zmora-judge#8]

**Comment by marcmos** [comment]
@maxmati, co się ma w tym konkretnie znaleźć? Może podejdziemy do tematu profesjonalnie i poprzestaniemy na zmiennych środowiskowych i argumentach?

**Comment by maxmati** [comment]
To issue się jest już nie aktualne obecny stan jest chyba ok. Zamykam.
